name: Build site
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install python
        uses: actions/setup-python@v7
        with:
          python-version: 3.x
          cache: pip
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Build
        run: properdocs build --strict
